# Generated by Django 4.2 on 2025-06-25 13:30

from django.db import migrations, models
import posts.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=240, verbose_name='Título')),
                ('post_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('post_image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=posts.models.get_file_path, variations={'large': {'height': 800, 'width': 1200}, 'medium': {'height': 600, 'width': 800}, 'thumb': {'crop': True, 'height': 200, 'width': 300}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
